backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "static/img"
collections:
  -   name: "pages"
      label: "Seitenübersicht"
      files:
      - file: "content/_index.md"
        label: "Startseite"
        name: "home"
        editor:
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          
      - file: "content/aktuelles.md"
        label: "Aktuelles"
        name: "aktuelles"
        editor: 
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" } 
      - file: "content/beratung.md"
        label: "Beratung"
        name: "beratung"
        editor: 
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/downloads.md"
        label: "Downloads"
        name: "downloads"
        editor: 
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - label: "Übersicht Downloads"
            name: "downloads" 
            widget: "list" 
            summary: '{{fields.title}}' 
            fields:
             - { label: "Beschreibung", name: "description", widget: "string" }  
             - { label: "Besitzer", name: "owner", widget: "string" } 
             - { label: "Zuletzt aktualisiert", name: "lastUpdated", widget: "string" }
             - { label: "Download", name: "file", widget: "file" }
             - { label: "Kategorie", name: "category", widget: "string" }
      - file: "content/erfa.md"
        label: "Erfa"
        name: "erfa"
        editor: 
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        editor: 
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "body", name: "body", widget: "markdown" } 
      - file: "content/partner.md"
        label: "Partner"
        name: "partner"
        editor: 
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "body", name: "body", widget: "markdown" } 
      - file: "content/seminare.md"
        label: "Seminare"
        name: "seminare"
        editor: 
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "body", name: "body", widget: "markdown" } 
      - file: "content/über-uns.md"
        label: "Über uns"
        name: "über-uns"
        editor: 
          preview: false
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "body", name: "body", widget: "markdown" }
         
      
                       
          
                            
      
          
        
